name: build-test-deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - 'main'

defaults:
  run:
    working-directory: .

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  client-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my-app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.17.0"
      - name:  Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test

  api-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api/Api
    steps:
      - uses: actions/checkout@v2
      - name:  Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build

  api-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api/Api/TestApi
    steps:
      - uses: actions/checkout@v2
      - name:  Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test